import crypto from "crypto";
import config from "../config";
import { PrismaClient } from "../generated/prisma";
import speakeasy from "speakeasy";

const prisma = new PrismaClient();

const ALGORITHM = "aes-256-gcm";
// Key must be 32 bytes for aes-256-gcm
// Ensure your MFA_ENCRYPTION_KEY in .env is appropriate (e.g., 64 hex chars)
const ENCRYPTION_KEY = Buffer.from(config.MFA_ENCRYPTION_KEY, "hex");
const IV_LENGTH = 16; // For AES-GCM, IV is typically 12 or 16 bytes. 16 is common.
const AUTH_TAG_LENGTH = 16;

/**
 * Encrypts MFA secret using AES-256-GCM.
 * Prepends IV to the ciphertext for storage.
 */
export const encryptMfaSecret = (secret: string): string => {
  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, ENCRYPTION_KEY, iv, {
    authTagLength: AUTH_TAG_LENGTH,
  });
  const encrypted = Buffer.concat([
    cipher.update(secret, "utf8"),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();
  // Prepend IV and AuthTag to the encrypted data. Store as hex.
  return Buffer.concat([iv, authTag, encrypted]).toString("hex");
};

/**
 * Decrypts MFA secret encrypted with AES-256-GCM.
 * Assumes IV and AuthTag are prepended to the ciphertext.
 */
export const decryptMfaSecret = (encryptedSecretHex: string): string => {
  const encryptedBuffer = Buffer.from(encryptedSecretHex, "hex");
  const iv = encryptedBuffer.subarray(0, IV_LENGTH);
  const authTag = encryptedBuffer.subarray(
    IV_LENGTH,
    IV_LENGTH + AUTH_TAG_LENGTH
  );
  const encrypted = encryptedBuffer.subarray(IV_LENGTH + AUTH_TAG_LENGTH);

  const decipher = crypto.createDecipheriv(ALGORITHM, ENCRYPTION_KEY, iv, {
    authTagLength: AUTH_TAG_LENGTH,
  });
  decipher.setAuthTag(authTag);

  const decrypted = Buffer.concat([
    decipher.update(encrypted),
    decipher.final(),
  ]);
  return decrypted.toString("utf8");
};

interface MfaSetupPayload {
  otpAuthUrl: string;
}

/**
 * Generates a new MFA secret for a user using speakeasy.
 * Stores the base32 secret encrypted.
 * Returns the otpauth:// URL.
 */
export const generateMfaSetup = async (
  userId: string,
  email: string
): Promise<MfaSetupPayload> => {
  // Generate secret using speakeasy
  const secret = speakeasy.generateSecret({
    name: `YourAppName (${email})`, // Use app name and user email
    issuer: "YourAppName", // Replace with your app name
  });

  // Encrypt the base32 version of the secret for storage
  const encryptedSecret = encryptMfaSecret(secret.base32);

  // Store encrypted secret, ensure MFA is not enabled yet
  await prisma.user.update({
    where: { id: userId },
    data: {
      mfaSecretEncrypted: encryptedSecret,
      mfaEnabled: false,
    },
  });

  // Return the otpauth_url generated by speakeasy
  return { otpAuthUrl: secret.otpauth_url! }; // Use non-null assertion as speakeasy should always return it
};

/**
 * Verifies the TOTP code using speakeasy.
 * If successful, marks MFA as enabled.
 */
export const verifyMfaSetup = async (
  userId: string,
  token: string
): Promise<boolean> => {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { mfaSecretEncrypted: true, mfaEnabled: true },
  });

  if (!user || !user.mfaSecretEncrypted || user.mfaEnabled) {
    console.warn(
      `[MFA Service] Attempt to verify MFA for user ${userId} in invalid state.`
    );
    return false;
  }

  try {
    // Decrypt the stored base32 secret
    const decryptedBase32Secret = decryptMfaSecret(user.mfaSecretEncrypted);

    // Verify the token using speakeasy
    const isValid = speakeasy.totp.verify({
      secret: decryptedBase32Secret,
      encoding: "base32",
      token: token,
      window: 1, // Allow for a 1-step time drift
    });

    if (!isValid) {
      return false;
    }

    // Token is valid, mark MFA as enabled
    await prisma.user.update({
      where: { id: userId },
      data: { mfaEnabled: true },
    });

    return true;
  } catch (error) {
    console.error(
      `[MFA Service] Error verifying MFA setup for user ${userId}:`,
      error
    );
    return false;
  }
};
