import crypto from "crypto";
import config from "../config";
import { PrismaClient } from "../generated/prisma";
import speakeasy from "speakeasy";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

const ALGORITHM = "aes-256-gcm";
// Key must be 32 bytes for aes-256-gcm
// Ensure your MFA_ENCRYPTION_KEY in .env is appropriate (e.g., 64 hex chars)
const ENCRYPTION_KEY = Buffer.from(config.MFA_ENCRYPTION_KEY, "hex");
const IV_LENGTH = 16; // For AES-GCM, IV is typically 12 or 16 bytes. 16 is common.
const AUTH_TAG_LENGTH = 16;

/**
 * Encrypts MFA secret using AES-256-GCM.
 * Prepends IV to the ciphertext for storage.
 */
export const encryptMfaSecret = (secret: string): string => {
  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, ENCRYPTION_KEY, iv, {
    authTagLength: AUTH_TAG_LENGTH,
  });
  const encrypted = Buffer.concat([
    cipher.update(secret, "utf8"),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();
  // Prepend IV and AuthTag to the encrypted data. Store as hex.
  return Buffer.concat([iv, authTag, encrypted]).toString("hex");
};

/**
 * Decrypts MFA secret encrypted with AES-256-GCM.
 * Assumes IV and AuthTag are prepended to the ciphertext.
 */
export const decryptMfaSecret = (encryptedSecretHex: string): string => {
  const encryptedBuffer = Buffer.from(encryptedSecretHex, "hex");
  const iv = encryptedBuffer.subarray(0, IV_LENGTH);
  const authTag = encryptedBuffer.subarray(
    IV_LENGTH,
    IV_LENGTH + AUTH_TAG_LENGTH
  );
  const encrypted = encryptedBuffer.subarray(IV_LENGTH + AUTH_TAG_LENGTH);

  const decipher = crypto.createDecipheriv(ALGORITHM, ENCRYPTION_KEY, iv, {
    authTagLength: AUTH_TAG_LENGTH,
  });
  decipher.setAuthTag(authTag);

  const decrypted = Buffer.concat([
    decipher.update(encrypted),
    decipher.final(),
  ]);
  return decrypted.toString("utf8");
};

interface MfaSetupPayload {
  otpAuthUrl: string;
}

/**
 * Generates a new MFA secret for a user using speakeasy.
 * Stores the base32 secret encrypted.
 * Returns the otpauth:// URL.
 */
export const generateMfaSetup = async (
  userId: string,
  email: string
): Promise<MfaSetupPayload> => {
  // Generate secret using speakeasy
  const secret = speakeasy.generateSecret({
    name: `YourAppName (${email})`, // Use app name and user email
    issuer: "YourAppName", // Replace with your app name
  });

  // Encrypt the base32 version of the secret for storage
  const encryptedSecret = encryptMfaSecret(secret.base32);

  // Store encrypted secret, ensure MFA is not enabled yet
  await prisma.user.update({
    where: { id: userId },
    data: {
      mfaSecretEncrypted: encryptedSecret,
      mfaEnabled: false,
    },
  });

  // Return the otpauth_url generated by speakeasy
  return { otpAuthUrl: secret.otpauth_url! }; // Use non-null assertion as speakeasy should always return it
};

/**
 * Verifies the TOTP code using speakeasy.
 * If successful, marks MFA as enabled and generates backup codes.
 * Returns the generated backup codes on success, otherwise null.
 */
export const verifyMfaSetup = async (
  userId: string,
  token: string
): Promise<string[] | null> => {
  // Return backup codes or null
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { mfaSecretEncrypted: true, mfaEnabled: true },
  });

  if (!user || !user.mfaSecretEncrypted || user.mfaEnabled) {
    console.warn(
      `[MFA Service] Attempt to verify MFA for user ${userId} in invalid state.`
    );
    return null;
  }

  try {
    const decryptedBase32Secret = decryptMfaSecret(user.mfaSecretEncrypted);

    const isValid = speakeasy.totp.verify({
      secret: decryptedBase32Secret,
      encoding: "base32",
      token: token,
      window: 1,
    });

    if (!isValid) {
      return null; // Invalid token
    }

    // Token is valid, now enable MFA and generate backup codes
    // Use transaction to ensure both happen or neither
    let backupCodes: string[] = [];
    await prisma.$transaction(async (tx) => {
      // 1. Mark MFA as enabled
      await tx.user.update({
        where: { id: userId },
        data: { mfaEnabled: true },
      });
      // 2. Generate and store backup codes (using separate function)
      // Note: generateAndStoreBackupCodes handles its own transaction internally for code storage
      // If it throws, the outer transaction will roll back the mfaEnabled update.
      backupCodes = await generateAndStoreBackupCodes(userId);
    });

    return backupCodes; // Return plain text codes on success
  } catch (error) {
    console.error(
      `[MFA Service] Error verifying MFA setup for user ${userId}:`,
      error
    );
    return null; // Return null on error
  }
};

/**
 * Verifies a TOTP code for login.
 * Returns userId on success, null on failure.
 */
export const verifyLoginMfa = async (
  userId: string,
  token: string
): Promise<string | null> => {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { mfaSecretEncrypted: true, mfaEnabled: true },
  });

  // User must exist, have MFA enabled, and have a secret stored
  if (!user || !user.mfaEnabled || !user.mfaSecretEncrypted) {
    console.warn(
      `[MFA Service] Attempt to verify login MFA for user ${userId} in invalid state.`
    );
    return null;
  }

  try {
    const decryptedBase32Secret = decryptMfaSecret(user.mfaSecretEncrypted);

    const isValid = speakeasy.totp.verify({
      secret: decryptedBase32Secret,
      encoding: "base32",
      token: token,
      window: 1, // Allow for time drift
    });

    return isValid ? userId : null;
  } catch (error) {
    console.error(
      `[MFA Service] Error verifying login MFA for user ${userId}:`,
      error
    );
    return null;
  }
};

// --- Backup Code Logic ---
const BACKUP_CODE_COUNT = 10;
const BACKUP_CODE_LENGTH = 8; // Length of each code
const BACKUP_CODE_SALT_ROUNDS = 10;

// Generates a single alphanumeric backup code
const generateSingleBackupCode = (length: number): string => {
  // Simple alphanumeric generation
  return crypto
    .randomBytes(Math.ceil(length / 2))
    .toString("hex")
    .slice(0, length)
    .toUpperCase();
};

/**
 * Generates and stores hashed backup codes for a user.
 * Deletes any existing codes for the user first.
 * Returns the array of *plain text* codes for the user to save.
 */
export const generateAndStoreBackupCodes = async (
  userId: string
): Promise<string[]> => {
  const plainTextCodes: string[] = [];
  const hashedCodesData: { codeHash: string; userId: string }[] = [];

  // Generate codes
  for (let i = 0; i < BACKUP_CODE_COUNT; i++) {
    const code = generateSingleBackupCode(BACKUP_CODE_LENGTH);
    plainTextCodes.push(code);
    // Hash the code before storing
    const codeHash = await bcrypt.hash(code, BACKUP_CODE_SALT_ROUNDS);
    hashedCodesData.push({ codeHash, userId });
  }

  // Store new codes in a transaction (delete old, create new)
  try {
    await prisma.$transaction(async (tx) => {
      // 1. Delete old codes
      await tx.backupCode.deleteMany({ where: { userId } });
      // 2. Create new codes
      await tx.backupCode.createMany({ data: hashedCodesData });
    });

    console.log(
      `[MFA Service] Generated ${BACKUP_CODE_COUNT} backup codes for user ${userId}.`
    );
    return plainTextCodes; // Return plain text codes ONLY on successful generation
  } catch (error) {
    console.error(
      `[MFA Service] Failed to store backup codes for user ${userId}:`,
      error
    );
    // If storing fails, don't give the codes to the user
    throw new Error("Failed to generate backup codes. Please try again.");
  }
};

/**
 * Verifies a provided backup code against stored hashes.
 * Marks the code as used if valid.
 * Returns userId on success, null on failure.
 */
export const verifyBackupCode = async (
  userId: string,
  providedCode: string
): Promise<string | null> => {
  // Fetch unused codes for the user
  const userCodes = await prisma.backupCode.findMany({
    where: { userId, used: false },
    select: { id: true, codeHash: true },
  });

  if (!userCodes || userCodes.length === 0) {
    console.warn(
      `[MFA Service] No unused backup codes found for user ${userId} during verification attempt.`
    );
    return null;
  }

  let matchedCodeId: string | null = null;

  // Compare provided code against each hash
  for (const codeRecord of userCodes) {
    const isValid = await bcrypt.compare(
      providedCode.toUpperCase(),
      codeRecord.codeHash
    );
    if (isValid) {
      matchedCodeId = codeRecord.id;
      break;
    }
  }

  if (!matchedCodeId) {
    return null;
  }

  try {
    await prisma.$transaction(async (tx) => {
      // Mark the code as used within the transaction
      await tx.backupCode.update({
        where: { id: matchedCodeId },
        data: { used: true },
      });
    });

    return userId;
  } catch (error) {
    console.error(
      `[MFA Service] Error marking backup code as used for user ${userId}:`,
      error
    );
    return null;
  }
};
